timeout: 1
default_entry: 1
interface_branding: Chef OS (x86_64 UEFI)

/Chef OS 1.0 (Higher-Half Kernel)
    protocol: limine
    kernel_path: boot():/boot/chef-kernel.elf
    comment: Chef OS Native from-scratch 64-bit kernel
